generated: '2026-10-03'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.cloudflare.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Dec 15 14:00:55 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: developers.cloudflare.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Dec 27 15:15:50 2026 GMT
  hsts: true
  hsts_max_age: 15552000
- host: api.cloudflare.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Nov 11 23:31:01 2026 GMT
  hsts: true
  hsts_max_age: 15552000
domains:
- domain: cloudflare.com
  dnssec: true
  caa:
  - 0 issuewild "pki.goog; cansignhttpexchanges=yes"
  - 0 issuewild "ssl.com"
  - 0 iodef "mailto:tls-abuse@cloudflare.com"
  - 0 issue "comodoca.com"
  - 0 issue "digicert.com; cansignhttpexchanges=yes"
  - 0 issue "letsencrypt.org"
  spf: true
  dmarc: true
  dmarc_policy: reject
